- name: Salesforce CLI Setup
  # You may pin to the exact commit or the version.
  # uses: karamchandanid/sfdx-setup@16c67b6461448e6e0f78e565326e4c8a8385799a
  uses: karamchandanid/sfdx-setup@v2
  with:
    # 
    user_name: 
    # 
    login_url: # optional, default is https://login.salesforce.com
    # combination of <password>:<security_token>
    password: 
    # Consumer Key of a connected App created within salesforce
    sfdc_client_id: 
    # Consumer Secret of a connected App created within salesforce
    sfdc_client_secret: 
